# Portmap Source Code - Nim

import std/os
import std/strutils
import std/sequtils

type
  Port = object
    name:      string
    direction: string
    width:     string

proc extractWidth(tokens: seq[string]): string =
  for tok in tokens:
    if tok.startsWith("["):
      return tok
  return "1"

proc extractNames(tokens: seq[string]): seq[string] =
  var names: seq[string] = @[]

  for tok in tokens:
    var name = tok.strip(chars = {' ', ',', ';', ')', '('})

    if name.len == 0: continue
    if name.startsWith("["): continue

    # Skip type qualifiers
    if name in ["wire", "reg", "logic", "signed", "unsigned"]: continue

    names.add(name)

  return names

proc parsePorts(filePath: string): seq[Port] =
  var ports: seq[Port] = @[]

  let content = readFile(filePath)
  let lines = content.split("\n")

  for rawLine in lines:
    var line = rawLine.strip()

    if line.len == 0: continue

    # Remove inline comments
    let commentIdx = line.find("//")
    if commentIdx >= 0:
      line = line[0 ..< commentIdx].strip()

    if line.len == 0: continue

    # Skip irrelevant lines
    if line.startsWith("/*") or
       line.startsWith("*")  or
       line.startsWith("endmodule") or
       line.startsWith("#(") or
       line.startsWith("parameter"):
      continue

    let lower = line.toLowerAscii()

    var direction = ""
    if lower.startsWith("input"):    direction = "input"
    elif lower.startsWith("output"): direction = "output"
    elif lower.startsWith("inout"):  direction = "inout"
    else: continue

    var tokens = line
      .replace(",", " , ")
      .splitWhitespace()

    if tokens.len < 2: continue

    let payload = tokens[1 .. ^1]

    let meaningful = payload.filterIt(
      it != "wire" and it != "reg" and it != "logic" and
      it != "signed" and it != "unsigned"
    )

    if meaningful.len == 0: continue

    let width = extractWidth(meaningful)

    let names = extractNames(meaningful)

    for name in names:
      var p: Port
      p.direction = direction
      p.width     = width
      p.name      = name
      ports.add(p)

  return ports

proc renderTable(ports: seq[Port], filePath: string) =
  let fname = filePath.extractFilename()

  echo ""
  echo "Port Map - " & fname
  echo ""

  var maxName = "Port".len
  var maxDir  = "Direction".len
  var maxWid  = "Width".len

  for p in ports:
    if p.name.len > maxName: maxName = p.name.len
    if p.direction.len > maxDir: maxDir = p.direction.len
    if p.width.len > maxWid: maxWid = p.width.len

  let col1 = maxName + 2
  let col2 = maxDir + 2
  let col3 = maxWid + 2

  proc line() =
    echo "+" & repeat("-", col1) &
         "+" & repeat("-", col2) &
         "+" & repeat("-", col3) & "+"

  line()
  echo "|" & alignLeft(" Port", col1) &
       "|" & alignLeft(" Direction", col2) &
       "|" & alignLeft(" Width", col3) & "|"
  line()

  for p in ports:
    echo "|" & alignLeft(" " & p.name, col1) &
         "|" & alignLeft(" " & p.direction, col2) &
         "|" & alignLeft(" " & p.width, col3) & "|"

  line()
  echo ""

proc renderMarkdown(ports: seq[Port], filePath: string) =
  let fname = filePath.extractFilename()

  echo ""
  echo "### Port Map - `" & fname & "`"
  echo ""
  echo "| Port | Direction | Width |"
  echo "|------|-----------|-------|"

  for p in ports:
    echo "| `" & p.name & "` | " & p.direction & " | " & p.width & " |"

  echo ""
  echo "> *Generated by [portmap](https://github.com/KARAN-D05/portmap-HDL/blob/main/portmap.nim) - Nim port extractor*"
  echo ""
  echo "> *Precompiled Binary Release [Portmap-linux-x64/portmap-windows-x64.exe](https://github.com/KARAN-D05/portmap-HDL/releases/tag/v1.0.0)**"

when isMainModule:

  if paramCount() < 1:
    echo "portmap - Verilog port extractor"
    echo "Usage:  portmap <file.v> [file2.v ...] [--md]"
    echo "Output: Pretty table (default) or Markdown with --md"
    quit(1)

  var useMarkdown = false

  for i in 1 .. paramCount():
    if paramStr(i) == "--md":
      useMarkdown = true

  for i in 1 .. paramCount():
    let path = paramStr(i)

    if path == "--md": continue

    if not fileExists(path):
      stderr.writeLine("ERROR: file not found: " & path)
      continue

    let ports = parsePorts(path)

    if ports.len == 0:
      stderr.writeLine("WARNING: no ports found in " & path)
    else:
      if useMarkdown:
        renderMarkdown(ports, path)
      else:
        renderTable(ports, path)
